
name: CI

on: [push]

jobs:
  pylint:
    runs-on: ubuntu-latest
    name: Linting with Pylint
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environment.yml
          activate-environment: tensorli
      - name: Lint with pylint
        run: |
          conda activate tensorli
          pylint tensorli/*.py test/*.py
  black:
    runs-on: ubuntu-latest
    name: Formatting with black
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environment.yml
          activate-environment: tensorli
      - name: Format with black
        run: |
          conda activate tensorli
          black tensorli/*.py test/*.py
  tests:
    runs-on: ubuntu-latest
    name: Running tests with pytest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environment.yml
          activate-environment: tensorli
      - name: Running tests with pytest
        run: |
          conda activate tensorli
          pytest -v
  mypy:
    runs-on: ubuntu-latest
    name: Running type checks with mypy
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environment.yml
          activate-environment: tensorli
      - name: Running type checks with mypy
        run: |
          conda activate tensorli
          mypy tensorli/ test/