
name: CI

on: [push]

jobs:
  pylint:
    runs-on: ubuntu-latest
    name: Linting with Pylint
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environment.yml
      - name: Lint with pylint
        run: |
          conda info
          pylint tensorli.py
  black:
    runs-on: ubuntu-latest
    name: Formatting with black
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environment.yml
      - name: Format with black
        run: |
          conda info
          black tensorli.py